### ISSUE TITLE
macOS 深色模式下显示错误

### ISSUE THREAD

**Issue by reputati0n** [gubeihc/blasting#1]
如图
![WX20220927-100855@2x](https://user-images.githubusercontent.com/30461763/192415032-1c74f0ac-0bfa-4c06-9ab6-7bdad8a53f95.png)

**Comment by gubeihc** [comment]
这个问题 我在写的时候就发现了，加了样式 他的底色就全白了，后续在想办法改改或者不加样式了 不过界面就有点丑了

**Comment by gubeihc** [comment]
已修复，新版本采用直接写好的样式。
