### ISSUE TITLE
运行之后提供QObject::startTimer: Timers can only be used with threads started with QThread

### ISSUE THREAD

**Issue by wkjmusz** [gubeihc/blasting#10]
PS E:\tool\04exp\02blasting> python.exe .\BLAST.py
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Ui_window.main() running at E:\tool\04exp\02blasting\BLAST.py:370>>

**Comment by gubeihc** [comment]
根据视频使用步骤来进行测试，如果遇到错误，请提供当前系统版本 python版本 测试目标 等信息 以供调试。
