### ISSUE TITLE
手动选择模式下无法浏览器正常访问URL

### ISSUE THREAD

**Issue by jiuyu123** [gubeihc/blasting#12]
环境：python3.8、python3.9
系统：Windows10
问题：使用手动模式开始爆破启动的浏览器并未访问指定url
![image](https://github.com/gubeihc/blasting/assets/49027153/1ce7c36d-2b2c-41ec-b541-bdbd6ef132e2)
控制台报错：

> 'Ui_window' object has no attribute 'on_response' 
![image](https://github.com/gubeihc/blasting/assets/49027153/d3476d4a-1254-4574-83e9-5386bffd9c76)

**Comment by gubeihc** [comment]
你这边本地启动了这个URL了吗。

**Comment by jiuyu123** [comment]
这个测试过其他站依然不行，本地开不开都不会在URL中体现

**Comment by gubeihc** [comment]
好的，我知道哪里的问题了，晚点更新一下 代码 在添加上最新功能
