### ISSUE TITLE
Mac启动爆破

### ISSUE THREAD

**Issue by RDPMind** [gubeihc/blasting#13]
❯ python3 BLAST.py
objc[2214]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/xxx/opt/anaconda3/lib/libQt5Core.5.15.2.dylib (0x10e03a400) and /Users/xxx/opt/anaconda3/lib/python3.9/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x114029390). One of the two will be used. Which one is undefined.
objc[2214]: Class KeyValueObserver is implemented in both /Users/xxx/opt/anaconda3/lib/libQt5Core.5.15.2.dylib (0x10e03a428) and /Users/xxx/opt/anaconda3/lib/python3.9/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x1140293b8). One of the two will be used. Which one is undefined.
objc[2214]: Class RunLoopModeTracker is implemented in both /Users/xxx/opt/anaconda3/lib/libQt5Core.5.15.2.dylib (0x10e03a478) and /xxx/xxxx/opt/anaconda3/lib/python3.9/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x114029408). One of the two will be used. Which one is undefined.
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.drawing: Layer-backing is always enabled.  QT_MAC_WANTS_LAYER/_q_mac_wantsLayer has no effect.
[1]    2214 segmentation fault  python3 BLAST.py

**Comment by gubeihc** [comment]
删除电脑上pyqt5的库，这里依赖冲突了
