### ISSUE TITLE
报错'Ui_window' object has no attribute 'on_response'

### ISSUE THREAD

**Issue by wxnsoul** [gubeihc/blasting#14]
MAC端
手动模式下打开的浏览器是空白页面,然后产生以下报错
<img width="1792" alt="image" src="https://github.com/gubeihc/blasting/assets/49633943/24f8b8a9-d854-470f-8006-46c9c74e1c57">
然后自动模式没有返回包信息
<img width="1234" alt="image" src="https://github.com/gubeihc/blasting/assets/49633943/180e0bd2-652e-4350-b3c1-3a612b99392c">
我知道密码是123456,但是两个模式都没有得到正确结果

**Comment by gubeihc** [comment]
更新代码，这个是之前的代码了 已经修复
