### ISSUE TITLE
好多误判 

### ISSUE THREAD

**Issue by cqrlhz** [gubeihc/blasting#16]
![image](https://github.com/gubeihc/blasting/assets/63200706/958f7716-f434-417f-9738-4a0e93cf29ca)
希望加一个 过滤 登录失败长度的开关，然后二次验证非登录失败的响应长度，提高准确性

**Comment by gubeihc** [comment]
误判这个不存在，本身就是通过title url 长度 来进行手工验证的，这里并不能判断所有系统是否登录成功，这个回显是正常的，
