### ISSUE TITLE
QObject::startTimer: Timers can only be used with threads started with QThread

### ISSUE THREAD

**Issue by pantao0317** [gubeihc/blasting#17]
![image](https://github.com/gubeihc/blasting/assets/81206154/847e5986-fdff-4512-b7aa-990b3158cac0)

**Comment by gubeihc** [comment]
使用python3.9 试试呢，

**Comment by xiaoxiaoler** [comment]
Python 3.9.13也会有这个问题，Python 3.10.5正常运行

**Comment by gubeihc** [comment]
Python  3.9.11 我这边是这个 没问题，具体到底是啥影响的 过些天结束了 在搭建环境测试一下

**Comment by pantao0317** [comment]
切换Python 3.10.5 版本正常运行，原版本3.8

**Comment by gubeihc** [comment]
环境无法复现，暂时关闭。

**Comment by gubeihc** [comment]
已修复这个问题，导入库的顺序不对导致初始化有问题
