### ISSUE TITLE
blast 3.1 无法显示全部UI,是不是我电脑有BUG

### ISSUE THREAD

**Issue by winezer0** [gubeihc/blasting#19]
测试环境 windows10 x64 Python 3.8.5

在blast 3.1中看不到手动和自动模式，攻击方式也没法选择，只支持sniper

![image](https://github.com/gubeihc/blasting/assets/46115146/cf371242-4d3b-4161-ac30-5ead335897ae)

在blast 2.1能正常打开UI

但是手动模式也只支持sniper

![image](https://github.com/gubeihc/blasting/assets/46115146/6a96bc76-d207-4918-a3ee-506ab3510bf0)

![image](https://github.com/gubeihc/blasting/assets/46115146/3bba59f6-0da2-4495-8ce3-13451e1b4b1c)

![image](https://github.com/gubeihc/blasting/assets/46115146/07744e70-8d82-451b-8e3f-356d26b22463)

执行爆破直接卡在这里了

**Comment by gubeihc** [comment]
2.1 版本我记得手动模式就sniper 没添加，3.1版本没办法复现出你那个问题，我这边虚拟机正常，你要不升级一下python版本，3.9， 然后程序目录不要放到存在中文的地址， pyqt6 删除本地pyqt5

**Comment by winezer0** [comment]
重新安装并使用python3.9.13解决该问题
