### ISSUE TITLE
遇到错误

### ISSUE THREAD

**Issue by lzfls** [gubeihc/blasting#21]
MAC系统M1芯片，CONDA下安装出现如下错误

 error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent, which is required to install pyproject.toml-based projects

**Comment by gubeihc** [comment]
未知错误，无法进行测试，建议更换版本并根据群文件演示视频安装
