### ISSUE TITLE
小tips

### ISSUE THREAD

**Issue by s1g0day** [gubeihc/blasting#27]
工具体验非常不错，特留下一些想法：

1、输出结果添加状态码，有些返回长度不一样的可以通过状态码判断

2、添加登录失败判断

可以定义一些关键词来判断是否登录失败，就跟验证码错误关键词一样。`通过判断登陆失败，反推可能就是登录成功`
```
登录失败|Login fail|用户名或密码错误|密码错误|登陆的帐号不存在|账号或密码错误|无效的用户信息|用户不正确
```
- 点击登录后的状态也无法准确判断，因为每个开发所使用的提示方式可能不同，目前已遇到的有三种：

  1、登录后通过alert弹窗的方式提示账密错误，此时可以先判断是否存在弹窗，如果存在的话则按下键盘的Enter键。但弹窗也存在一些无法识别Enter的；
 2、通过302跳转新页面提示账密错误，此时可以通过计算302之后的页面长度来判断；
 3、直接在页面显示账密错误，这种情况可以判断返回包大小。如果长度不一样的话，可以人工查看返回的状态码，来判断是否存在登录跳转的信息。

以上仅为个人观点，望师傅能够酌情采纳。

**Comment by gubeihc** [comment]
好 我想一想 怎么添加更好用

**Comment by gubeihc** [comment]
输出结果添加状态码已采纳，但是登录判断这个逻辑还是欠缺，你这种考虑的太少了，请求状态大概分好几种，比如登录失败、登录成功、账户锁定、waf拦截、有些关键词不是你请求几次就能出现的

**Comment by s1g0day** [comment]
感谢师傅采纳，登录判断这个逻辑确实欠缺很多，仅仅是为师傅提供一个思路。

关键词不足可以根据实战不断追加，但登录成功的关键词无法准确预测，这也是我`通过判断登陆失败，反推可能就是登录成功`的思路来源。登录失败的情况可以先手工测试出所有可能失败的情况，在考虑是否使用工具跑。像账户锁定这种就不用跑了，waf拦截的变数比较多，在必须爆破的情况下只能根据场景编写单独脚本，5秒盾、人机判断同样如此。

但关键词匹配也不是通用的，还有一种情况是通过js函数返回，无法直接通过源代码获取到状态码，可以使用xpath定位关键词位置来获取，或者通过js调试。

所以在特殊情况下，一般还是单个写脚本去跑，目前个人已知的情况，尚未存在合适的工具能够容纳所有情况，且大多数工具已经停更。而我提到的三种情况，应该是个人感觉遇到最频繁且通用的场景。工具的目的只能去匹配大多数场景，不断更新就是不断去适配新场景的过程。当然个人精力及经验有限，能够做到适配大多数情况就很好了。
