### ISSUE TITLE
pip 安装失败

### ISSUE THREAD

**Issue by kN6jq** [gubeihc/blasting#3]
![image](https://user-images.githubusercontent.com/27048404/200215057-5752a2ab-85ab-4b34-be99-ca6794fe1e8e.png)

![image](https://user-images.githubusercontent.com/27048404/200215089-a8ab8f97-bd36-4ef4-8f06-98946e64684c.png)

安装完后提示未安装exceptions

```
Traceback (most recent call last):
  File "BLAST.py", line 12, in <module>
    from docx import Document
  File "C:\Python38\lib\site-packages\docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'

```

**Comment by gubeihc** [comment]
pip3 install. python-docx==0.8.11
