### ISSUE TITLE
脚本运行报错

### ISSUE THREAD

**Issue by Tivon1995** [gubeihc/blasting#4]
python BLAST.py
Traceback (most recent call last):
  File "BLAST.py", line 977, in <module>
    ui.setui_text(mainwindows)
  File "BLAST.py", line 631, in setui_text
    self.setupUi(window)
  File "BLAST.py", line 662, in setupUi
    window.move((screen.width() - size.width()) / 2,
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

**Comment by Tivon1995** [comment]
BLAST.py 第 662 行使用 int()转换可能出现的float参数值
改为 window.move(int((screen.width() - size.width())/2), int((screen.height() - size.height())/2))

**Comment by gubeihc** [comment]
秀呀，窗口居然还有这个错误 晚点加上
