### ISSUE TITLE
win11运行爆破任务没有反应

### ISSUE THREAD

**Issue by rechallage** [gubeihc/blasting#9]
![image](https://github.com/gubeihc/blasting/assets/85208463/5132d968-1e05-4d07-8bb8-a49cf4d37919)
![image](https://github.com/gubeihc/blasting/assets/85208463/01bdb7db-8a12-4a83-b9f8-e0fae1b3d522)
我运行后下面没有跑起来

**Comment by gubeihc** [comment]
源码使用需要安装浏览器
python3 -m playwright install
可以点击浏览器那个圈 看一下界面 ，

**Comment by rechallage** [comment]
但是那个圈点了没有反应

**Comment by gubeihc** [comment]
你这个就是环境问题了，试试给这个库卸载了 然后重新安装，浏览器按钮开启 点击运行没反应 那就是代码并没有从你的系统上获取到默认的浏览器路径，看一下你ide运行的python 跟终端的python 是不是一个
